table 'Factview Forecast'
	lineageTag: 960f93fb-28f8-4f46-a558-2438861f8afc

	column 'Forecast Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fe96f05a-2ace-4bd2-a6f7-a72424ac07c8
		summarizeBy: none
		sourceColumn: Forecast Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Region Territory'
		dataType: string
		lineageTag: 22cb4c07-10e5-4ac4-9210-c26845fd01f6
		summarizeBy: none
		sourceColumn: Region Territory

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: a1bf72d3-b1d5-44c4-9baa-4aeb6663de54
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	column 'Forecast (EUR)'
		dataType: int64
		formatString: 0
		lineageTag: 4a1130d0-8b19-4a33-96c4-71d16550a11c
		summarizeBy: sum
		sourceColumn: Forecast (EUR)

		annotation SummarizationSetBy = Automatic

	partition 'Factview Forecast' = m
		mode: import
		source =
				let
				    Source = Sql.Database("te3-training-eu.database.windows.net", "SpacePartsCoDW"),
				    Factview_Forecast = Source{[Schema="Factview",Item="Forecast"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(Factview_Forecast,{"Forecast Month", "Region Territory", "Product Type", "Forecast (EUR)"}),
				    #"Kept First Rows" = Table.FirstN(#"Removed Other Columns",10000)
				in
				    #"Kept First Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

